# Generated by Selenium IDE
import time

from selenium import webdriver
from selenium.webdriver.common.by import By
# from selenium.webdriver.common.actions.mouse_button import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait


class TestHogwarts():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.driver.set_window_size(1552, 840)
        self.driver.get("https://testerhome.com/")
        #隐式等待
        self.driver.implicitly_wait(5)
        self.wait = WebDriverWait(self.driver, 30)

    def test_testseach(self):
        #self.driver.find_element(By.LINK_TEXT, "社团").click()
        # todo:显示等待
        element=(By.PARTIAL_LINK_TEXT, 'MTSC2020 中国互联网测试开发大会议题征集')
        self.wait.until(expected_conditions.element_to_be_clickable(element))
        self.driver.find_element(*element).click()
        self.driver.find_element(By.CSS_SELECTOR, '.btn-default .fa-list').click()
        #self.driver.find_element((By.PARTIAL_LINK_TEXT,'.list .toc-level-2:nth-child(4) > a')).click()
        #time.sleep(5)
        #self.driver.find_element((By.LINK_TEXT, '议题征集流程')).click()
        self.driver.find_element(By.XPATH,'//*[@id="main"]/div/div[1]/div[1]/div[2]/div/div/div/ul/li[4]/a').click()

    def teardown_method(self):
        time.sleep(5)
        self.driver.quit()

