# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
# from selenium.webdriver.common.actions.mouse_button import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestHogwarts():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.driver.set_window_size(1552, 840)
        self.driver.get("https://testerhome.com/")
        #隐式等待
        self.driver.implicitly_wait(5)
        #self.wait = WebDriverWait(self.driver, 30)

    def wait(self, timeout, method):
        WebDriverWait(self.driver, timeout).until(method)

    def test_testseach(self):
        self.driver.find_element(By.LINK_TEXT, "社团").click()
        # todo:显示等待
        element=(By.PARTIAL_LINK_TEXT, '霍格沃兹测试学院')
        self.wait(10, expected_conditions.element_to_be_clickable(element))
        # WebDriverWait(self.driver,10).until((lambda x:self.driver.find_element(element)))
        self.driver.find_element(*element).click()    # *element拆箱，把一个元组拆成2个元素
        #尽量使用css的定位方式，link有可能导致解析元素出现异常
        # 使用css比link更好用
        #self.driver.find_element(By.CSS_SELECTOR, '[data-name="霍格沃兹测试学院"]').click()
        # done:隐式等待
        self.driver.find_element(By.CSS_SELECTOR, '.topic:nth-child(1) .title a').click()



    def test_mtsc2020(self):
        self.driver.get("https://testerhome.com/topics/21805")
        print(self.driver.window_handles)
        #self.driver.switch_to.frame(0)
        sub = (By.PARTIAL_LINK_TEXT,'第六届中国互联网测试开发大会')
        self.wait(40, expected_conditions.element_to_be_clickable(sub))
        self.driver.find_element(*sub).click()
        print(self.driver.window_handles)
        self.wait(10, lambda x: len(self.driver.window_handles) > 1)
        self.driver.switch_to.window(self.driver.window_handles[1])
        self.driver.find_element(By.LINK_TEXT,'演讲申请').click()

    def teardown_method(self):
        time.sleep(5)
        self.driver.quit()

